/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author joshu
 */
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.JLabel;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */

    public MainFrame() {
        setIconImage(new ImageIcon(getClass().getResource("/logos/petAdoptionSystemLogo.png")).getImage());
        initComponents();
        setSize(900, 480);
        setLocationRelativeTo(null); // Center on screen

    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        adopterButton = new javax.swing.JButton();
        petButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 183, 91));
        mainPanel.setPreferredSize(new java.awt.Dimension(700, 500));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adopterButton.setBackground(new java.awt.Color(204, 204, 204));
        adopterButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        adopterButton.setForeground(new java.awt.Color(0, 0, 0));
        adopterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/adopters__2_-removebg-preview.png"))); // NOI18N
        adopterButton.setBorder(null);
        adopterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adopterButtonActionPerformed(evt);
            }
        });
        mainPanel.add(adopterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, 217));

        petButton.setBackground(new java.awt.Color(204, 204, 204));
        petButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        petButton.setForeground(new java.awt.Color(0, 0, 0));
        petButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/petlogo-removebg-preview_1.png"))); // NOI18N
        petButton.setBorder(null);
        petButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petButtonActionPerformed(evt);
            }
        });
        mainPanel.add(petButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 336, 217));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/text-1745891060932.png"))); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 580, 70));

        jPanel1.setBackground(new java.awt.Color(255, 141, 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adopterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adopterButtonActionPerformed
        adopterFrame adopter = new adopterFrame();
        adopter.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adopterButtonActionPerformed

    private void petButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petButtonActionPerformed
        System.out.println("Opening petFrame, this = " + this);
        petFrame pet = new petFrame();
        pet.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_petButtonActionPerformed

     

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adopterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton petButton;
    // End of variables declaration//GEN-END:variables
}
