/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author joshu
 */
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import dbconnection.ConnectionMySQL;
import javax.swing.SwingUtilities;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.JLabel;


public class petFrame extends javax.swing.JFrame {

    /**
     * Creates new form petFrame
     */
    private int selectedRowIndex = -1;
    private adoptForm adoptWindow;  // Declare this at the class level

    private adopterFrame adopter;

    
    public petFrame() {
        setTitle("Pet Adoption System");
        initComponents();
        loadPetData();
        updateCountLabel();
        setIconImage(new ImageIcon(getClass().getResource("/logos/petAdoptionSystemLogo.png")).getImage());

        
        petTable.getTableHeader().setBackground(Color.BLACK);
        petTable.getTableHeader().setForeground(Color.WHITE);
        petTable.getTableHeader().setForeground(Color.BLACK);
        petTable.getTableHeader().setFont(new Font("Arial", Font.PLAIN, 12));
        setSize(950, 520);
        setLocationRelativeTo(null); // Center on screen

        // Disable buttons initially
        updateButton.setEnabled(false);
        deleteButton.setEnabled(false);
        adoptButton.setEnabled(false);
        
       
        addTableClickListener();
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        adoptButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        petTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        adopted = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        available = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(225, 235, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(251, 250, 251));
        jPanel2.setPreferredSize(new java.awt.Dimension(990, 543));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateButton.setBackground(new java.awt.Color(25, 129, 240));
        updateButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("UPDATE PET");
        updateButton.setFocusPainted(false);       // Removes focus outline
        updateButton.setBorderPainted(false);      // Hides any border drawing
        updateButton.setBorder(BorderFactory.createEmptyBorder());
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel2.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 146, 61));

        addButton.setBackground(new java.awt.Color(10, 176, 109));
        addButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD PET");
        addButton.setBorder(null);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 146, 61));

        adoptButton.setBackground(new java.awt.Color(136, 45, 252));
        adoptButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        adoptButton.setForeground(new java.awt.Color(255, 255, 255));
        adoptButton.setText("ADOPT!");
        adoptButton.setBorder(null);
        adoptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptButtonActionPerformed(evt);
            }
        });
        jPanel2.add(adoptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 146, 61));

        exitButton.setBackground(new java.awt.Color(252, 57, 45));
        exitButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("EXIT");
        exitButton.setBorder(null);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 146, 65));

        deleteButton.setBackground(new java.awt.Color(252, 161, 45));
        deleteButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("DELETE");
        deleteButton.setBorder(null);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel2.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 146, 61));

        petTable.setBackground(new java.awt.Color(255, 255, 255));
        petTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Pet ID", "Pet Name", "Species", "Breed", "Age", "Status"
            }
        ));
        jScrollPane1.setViewportView(petTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 610, 470));

        jPanel3.setBackground(new java.awt.Color(255, 183, 91));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Available Pets");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Adopted Pets");

        jPanel4.setBackground(new java.awt.Color(251, 250, 251));

        adopted.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        adopted.setForeground(new java.awt.Color(255, 141, 4));
        adopted.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(adopted)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adopted, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel5.setBackground(new java.awt.Color(251, 250, 251));

        available.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        available.setForeground(new java.awt.Color(255, 141, 4));
        available.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(available)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(available, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        jPanel6.setBackground(new java.awt.Color(255, 141, 4));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 42)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("PETS");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void updateCountLabel(){
        DefaultTableModel model = (DefaultTableModel) petTable.getModel();
        int availableCount = 0;
        int adoptedCount = 0;

        for (int i = 0; i < model.getRowCount(); i++) {
            String status = model.getValueAt(i, 5).toString(); // adjust index
            if (status.equalsIgnoreCase("Available")) {
                availableCount++;
            }
        }

        for (int i = 0; i < model.getRowCount(); i++) {
            String status = model.getValueAt(i, 5).toString(); // adjust index
            if (status.equalsIgnoreCase("Adopted")) {
                adoptedCount++;
            }
        }

        available.setText(String.valueOf(availableCount));
        adopted.setText(String.valueOf(adoptedCount));
        

    }
    
    

    
    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selectedRow = petTable.getSelectedRow(); // Get selected row index

        if (selectedRow == -1) { // No row selected
            JOptionPane.showMessageDialog(this, "Please select a pet to delete.");
            return;
        }

        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this pet?",
            "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Get PetID from the selected row (assuming PetID is in column 0)
        int petID = (int) petTable.getValueAt(selectedRow, 0);

        try (Connection conn = ConnectionMySQL.getConnection();
            PreparedStatement stmt = conn.prepareStatement("DELETE FROM pets WHERE PetID = ?")) {

            stmt.setInt(1, petID);
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Pet deleted successfully!");
                loadPetData(); // ✅ Refresh table
                updateCountLabel();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete pet.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: Cannot Delete Pets that are already Adopted!");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void adoptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptButtonActionPerformed
        int selectedRow = petTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a pet to adopt.");
            return;
        }

        // Get PetID from the selected row
        int petId = (int) petTable.getValueAt(selectedRow, 0); // assuming PetID is in column 0
        String currentStatus = petTable.getValueAt(selectedRow, 5).toString(); // assuming status is in column 5

        if ("Adopted".equalsIgnoreCase(currentStatus)) {
            JOptionPane.showMessageDialog(this, "This pet has already been adopted.");
            return;
        }

        // Only open a new form if none is open
        if (adoptWindow == null) {
            adopterFrame adopter = new adopterFrame(); // ✅ create adopter frame
            adoptWindow = new adoptForm(adopter, this, petId); // ✅ pass it to adoptForm
            adoptWindow.setVisible(true);

            adoptWindow.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    adoptWindow = null;
                }
            });
        } else {
            adoptWindow.setVisible(true);
        }
    }//GEN-LAST:event_adoptButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addForm add = new addForm(this);
        add.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        int selectedRow = petTable.getSelectedRow(); // Your table name here

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a pet to update.");
            return;
        }

        // ✅ Get values from selected row (adjust indexes based on your table column order)
        int petID = (int) petTable.getValueAt(selectedRow, 0);
        String petName = petTable.getValueAt(selectedRow, 1).toString();
        String species = petTable.getValueAt(selectedRow, 2).toString();
        String breed = petTable.getValueAt(selectedRow, 3).toString();
        int age = Integer.parseInt(petTable.getValueAt(selectedRow, 4).toString());
        String status = petTable.getValueAt(selectedRow, 5).toString();

        // ✅ Open the updateForm with data
        updateForm updatePetForm = new updateForm(this, petID, petName, species, breed, age, status);
        updatePetForm.setVisible(true);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void addTableClickListener() {
            petTable.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    selectedRowIndex = petTable.getSelectedRow();
                    if (selectedRowIndex != -1) {
                        updateButton.setEnabled(true);
                        deleteButton.setEnabled(true);
                        adoptButton.setEnabled(true);
                    }
                }
            });
    }
    
    public int getSelectedPetId() {
        int selectedRow = petTable.getSelectedRow(); // Replace petTable with your actual JTable variable name

        if (selectedRow == -1) {
            throw new IllegalStateException("Please select a pet from the table.");
        }

        // Assuming PetID is in column 0
        Object petIdValue = petTable.getValueAt(selectedRow, 0);
        return Integer.parseInt(petIdValue.toString());
    }
    
    

    
    
   // Load pet data from the database
    public void loadPetData() {
    DefaultTableModel model = (DefaultTableModel) petTable.getModel();
    model.setRowCount(0); // Clear any existing rows

    String sql = "SELECT PetID, PetName, Species, Breed, Age, Status FROM pets";

    try (Connection conn = ConnectionMySQL.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {

        // Loop through the result set and add rows to the table
        while (rs.next()) {
            Object[] row = new Object[6];
            row[0] = rs.getInt("PetID");
            row[1] = rs.getString("PetName");
            row[2] = rs.getString("Species");
            row[3] = rs.getString("Breed");
            row[4] = rs.getInt("Age");
            row[5] = rs.getString("Status");
            model.addRow(row);
        }
        
        // Optionally force the table to update:
        petTable.revalidate();
        petTable.repaint();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading table data: " + e.getMessage());
    }
}

    
    private void adoptSelectedPet() {
      int selectedRow = petTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a pet to adopt.");
            return;
        }

        // Get PetID from the selected row
        int petId = (int) petTable.getValueAt(selectedRow, 0); // assuming PetID is in column 0
        String currentStatus = petTable.getValueAt(selectedRow, 5).toString(); // assuming status is column 5

        if ("Adopted".equalsIgnoreCase(currentStatus)) {
            JOptionPane.showMessageDialog(this, "This pet has already been adopted.");
            return;
        }
}


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mainFrame = new MainFrame();
                new petFrame().setVisible(true); // Pass mainFrame to petFrame constructor
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton adoptButton;
    private javax.swing.JLabel adopted;
    private javax.swing.JLabel available;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable petTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
