/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author joshu
 */

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import dbconnection.ConnectionMySQL;
import javax.swing.SwingUtilities;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
public class updateAdopterForm extends javax.swing.JFrame {

    /**
     * Creates new form updateAdopterForm
     */
    
    private int adoptionID;
    private JFrame parentFrame;

    public updateAdopterForm(JFrame parent,int adoptionID, int adopterID, String adopterName, String contact, String dateAdopted) {
        initComponents();
        this.adoptionID = adoptionID;
        this.parentFrame = parent;
        setIconImage(new ImageIcon(getClass().getResource("/logos/petAdoptionSystemLogo.png")).getImage());

        setSize(420, 490);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        txtNewAdopterId.setText(String.valueOf(adopterID));
        txtNewAdopterName.setText(adopterName);
        txtNewContact.setText(contact);
        // Convert from yyyy-MM-dd to MM-dd-yy
        try {
            SimpleDateFormat dbFormat = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat displayFormat = new SimpleDateFormat("MM-dd-yy");
            java.util.Date parsedDate = dbFormat.parse(dateAdopted);
            String formattedDate = displayFormat.format(parsedDate);
            txtNewDateAdopted.setText(formattedDate);
        } catch (ParseException e) {
            txtNewDateAdopted.setText(dateAdopted); // fallback to raw value
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNewContact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNewAdopterId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNewAdopterName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNewDateAdopted = new javax.swing.JTextField();
        submitNewAdoptButton = new javax.swing.JButton();
        cancelNewAdoptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 247, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 450));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("New Adopter Information");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("New Adopter No.");

        txtNewContact.setBackground(new java.awt.Color(255, 255, 255));
        txtNewContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtNewContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewContactActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Adopter No.");

        txtNewAdopterId.setBackground(new java.awt.Color(255, 255, 255));
        txtNewAdopterId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtNewAdopterId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewAdopterIdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("New Contact");

        txtNewAdopterName.setBackground(new java.awt.Color(255, 255, 255));
        txtNewAdopterName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtNewAdopterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewAdopterNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("New Date Adopted");

        txtNewDateAdopted.setBackground(new java.awt.Color(255, 255, 255));
        txtNewDateAdopted.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtNewDateAdopted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewDateAdoptedActionPerformed(evt);
            }
        });

        submitNewAdoptButton.setBackground(new java.awt.Color(13, 124, 79));
        submitNewAdoptButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submitNewAdoptButton.setForeground(new java.awt.Color(255, 255, 255));
        submitNewAdoptButton.setText("Submit");
        submitNewAdoptButton.setBorder(null);
        submitNewAdoptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitNewAdoptButtonActionPerformed(evt);
            }
        });

        cancelNewAdoptButton.setBackground(new java.awt.Color(255, 51, 51));
        cancelNewAdoptButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancelNewAdoptButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelNewAdoptButton.setText("Cancel");
        cancelNewAdoptButton.setBorder(null);
        cancelNewAdoptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNewAdoptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtNewContact, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewAdopterName, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewAdopterId, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNewDateAdopted, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelNewAdoptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitNewAdoptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewAdopterId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewAdopterName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewContact, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewDateAdopted, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitNewAdoptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelNewAdoptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewContactActionPerformed

    private void txtNewAdopterIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewAdopterIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewAdopterIdActionPerformed

    private void txtNewAdopterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewAdopterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewAdopterNameActionPerformed

    private void txtNewDateAdoptedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewDateAdoptedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewDateAdoptedActionPerformed

    private void submitNewAdoptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitNewAdoptButtonActionPerformed
        String newAdopterIdText = txtNewAdopterId.getText().trim();
        String newAdopterName = txtNewAdopterName.getText().trim();
        String newContact = txtNewContact.getText().trim();
        String newDateAdopted = txtNewDateAdopted.getText().trim();

        // Input validation
        if (newAdopterIdText.isEmpty() || newAdopterName.isEmpty() || newContact.isEmpty() || newDateAdopted.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        int newAdopterId;
        try {
            newAdopterId = Integer.parseInt(newAdopterIdText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Adopter ID must be a valid number.");
            return;
        }

        java.sql.Date sqlDate;
        try {
            SimpleDateFormat inputFormat = new SimpleDateFormat("MM-dd-yy");
            inputFormat.setLenient(false); // Strict parsing
            java.util.Date parsedDate = inputFormat.parse(newDateAdopted);
            sqlDate = new java.sql.Date(parsedDate.getTime());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Please enter the date in MM-dd-yy format (e.g., 4-25-25).");
            return;
        }

        // Update in database
        try (Connection conn = ConnectionMySQL.getConnection();
             PreparedStatement stmt = conn.prepareStatement(
                 "UPDATE adoptions SET AdopterID=?, AdopterName=?, Contact=?, DateAdopted=? WHERE AdoptionID=?")) {

            stmt.setInt(1, newAdopterId);
            stmt.setString(2, newAdopterName);
            stmt.setString(3, newContact);
            stmt.setDate(4, sqlDate);
            stmt.setInt(5, adoptionID); // ✅ Make sure this is declared in your class

            int rowsAffected = stmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Adopter updated successfully!");

                if (parentFrame instanceof adopterFrame) {
                    ((adopterFrame) parentFrame).loadAdoptionData();
                }

                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Update failed. Adoption record not found.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_submitNewAdoptButtonActionPerformed

    private void cancelNewAdoptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNewAdoptButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelNewAdoptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelNewAdoptButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitNewAdoptButton;
    private javax.swing.JTextField txtNewAdopterId;
    private javax.swing.JTextField txtNewAdopterName;
    private javax.swing.JTextField txtNewContact;
    private javax.swing.JTextField txtNewDateAdopted;
    // End of variables declaration//GEN-END:variables
}
