/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author joshu
 */
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import dbconnection.ConnectionMySQL;
import javax.swing.SwingUtilities;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class adoptForm extends javax.swing.JFrame {

    /**
     * Creates new form adoptForm
     */
    
    private adopterFrame adopterFrame;
    private int petId;

    public adoptForm(adopterFrame adopterFrame, int petId  ) {
        initComponents();;
        this.adopterFrame = adopterFrame;
        this.petId = petId;
        setSize(420, 490);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    private void addAdopterToDatabase() {
        String adopterIdText = txtAdopterId.getText();
        String adopterName = txtAdopterName.getText();
        String adopterContact = txtAdopterContact.getText();
        String dateAdoptedText = txtDateAdopted.getText();

        if (adopterIdText.isEmpty() || adopterName.isEmpty() || adopterContact.isEmpty() || dateAdoptedText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        int adopterId;
        try {
            adopterId = Integer.parseInt(adopterIdText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Adopter ID must be a valid number.");
            return;
        }

        String formattedDate;
        try {
            SimpleDateFormat inputFormat = new SimpleDateFormat("M-d-yy");
            SimpleDateFormat dbFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date parsedDate = inputFormat.parse(dateAdoptedText);
            formattedDate = dbFormat.format(parsedDate);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please use M-d-yy (e.g., 4-17-25).");
            return;
        }

        try (Connection conn = ConnectionMySQL.getConnection()) {

            // ✅ Insert all adopter + pet data into one row
            String insertAdoptionSQL = "INSERT INTO adoptions (AdopterID, AdopterName, Contact, PetID, DateAdopted) VALUES (?, ?, ?, ?, ?)";
            try (PreparedStatement stmt = conn.prepareStatement(insertAdoptionSQL)) {
                stmt.setInt(1, adopterId);
                stmt.setString(2, adopterName);
                stmt.setString(3, adopterContact);
                stmt.setInt(4, this.petId);
                stmt.setString(5, formattedDate);
                stmt.executeUpdate();
            }

            // ✅ Update pet status
            String updateStatusSQL = "UPDATE pets SET Status = 'Adopted' WHERE PetID = ?";
            try (PreparedStatement stmt = conn.prepareStatement(updateStatusSQL)) {
                stmt.setInt(1, petId);
                stmt.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Adopter and adoption recorded successfully!");
            adopterFrame.loadAdoptionData();
            System.out.println("DISPOSING adoptForm NOW"); // Debug print
            this.dispose(); // This should close the window
            this.dispose();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
}



    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAdopterId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDateAdopted = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAdopterName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        submitAdoptButton = new javax.swing.JButton();
        cancelAdoptButton = new javax.swing.JButton();
        txtAdopterContact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 247, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Adopter Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtAdopterId.setBackground(new java.awt.Color(255, 255, 255));
        txtAdopterId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtAdopterId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdopterIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtAdopterId, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 79, 388, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Adopter ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, -1, -1));

        txtDateAdopted.setBackground(new java.awt.Color(255, 255, 255));
        txtDateAdopted.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtDateAdopted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateAdoptedActionPerformed(evt);
            }
        });
        jPanel1.add(txtDateAdopted, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 334, 388, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Adopter Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 141, -1, -1));

        txtAdopterName.setBackground(new java.awt.Color(255, 255, 255));
        txtAdopterName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtAdopterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdopterNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtAdopterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 164, 388, 50));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contact");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 220, -1, -1));

        submitAdoptButton.setBackground(new java.awt.Color(13, 124, 79));
        submitAdoptButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submitAdoptButton.setForeground(new java.awt.Color(255, 255, 255));
        submitAdoptButton.setText("Submit");
        submitAdoptButton.setBorder(null);
        submitAdoptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAdoptButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitAdoptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 408, 90, 35));

        cancelAdoptButton.setBackground(new java.awt.Color(255, 51, 51));
        cancelAdoptButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancelAdoptButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelAdoptButton.setText("Cancel");
        cancelAdoptButton.setBorder(null);
        cancelAdoptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAdoptButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelAdoptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 408, 90, 35));

        txtAdopterContact.setBackground(new java.awt.Color(255, 255, 255));
        txtAdopterContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtAdopterContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdopterContactActionPerformed(evt);
            }
        });
        jPanel1.add(txtAdopterContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 243, 388, 50));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Date Adopted");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 311, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdopterIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdopterIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdopterIdActionPerformed

    private void txtDateAdoptedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateAdoptedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateAdoptedActionPerformed

    private void txtAdopterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdopterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdopterNameActionPerformed

    private void submitAdoptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAdoptButtonActionPerformed
        addAdopterToDatabase();
    }//GEN-LAST:event_submitAdoptButtonActionPerformed

    private void cancelAdoptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAdoptButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelAdoptButtonActionPerformed

    private void txtAdopterContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdopterContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdopterContactActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelAdoptButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitAdoptButton;
    private javax.swing.JTextField txtAdopterContact;
    private javax.swing.JTextField txtAdopterId;
    private javax.swing.JTextField txtAdopterName;
    private javax.swing.JTextField txtDateAdopted;
    // End of variables declaration//GEN-END:variables
}
